### ISSUE TITLE
Projektidee Wohngemeinschaft GDW19/20

### ISSUE THREAD

**Issue by Spirit344** [Spirit344/gdw_anspach_heynckes#2]
Bitte lesen Sie den [Eintrag](https://github.com/Spirit344/gdw_anspach_heynckes/wiki/Projektidee) in unserem Wiki!

**Comment by KrumnowTHKoeln** [comment]
Hallo, 
auch wenn mir nicht ganz klar ist, warum Sie deshalb ein Ticket erstellen, allerdings verlinken Sie bei solchen Anlässen doch bitte direkt zu Ihrer Wikiseite.

Beispielweise so: 
Link: [Projektidee](https://github.com/Spirit344/gdw_anspach_heynckes/wiki/Projektidee) 
Code: `[Projektidee](https://github.com/Spirit344/gdw_anspach_heynckes/wiki/Projektidee)`

Beste Grüße

**Comment by Spirit344** [comment]
Hallo Herr @KrumnowTHKoeln ,
wir haben im Ilias einen Eintrag unter der letzten Vorlesung gefunden, dass ein Issue zur Projektidee erstellt werden soll und den Mentoren zugewiesen werden soll. Sie haben ja heute bereits unsere Idee gehört, vielleicht ist das ganze für Herrn Fischer noch interessant.

Vielen Dank und Beste Grüße

**Comment by KrumnowTHKoeln** [comment]
Das war mir noch nicht bekannt. Okay.
